const INCONSISTENT_NAME = 'INCONSISTENT_NAME';
const INVALID_EMAIL = 'INVALID_EMAIL';
const WEEK_PASSWORD = 'WEEK_PASSWORD';
const EMAIL_ALREDY_EXISTS = 'EMAIL_ALREDY_EXISTS';

module.exports = {
  INCONSISTENT_NAME,
  INVALID_EMAIL,
  WEEK_PASSWORD,
  EMAIL_ALREDY_EXISTS,
};